
#  Contractor.create({
#         "id": 1,
#         "company": "R&M",
#         "first_name": "Dev",
#         "last_name": "Dav",
#         "street_address": "Madison Ave",
#         "city": "Las Vegas",
#         "state": "NV",
#         "zip": "12345",
#         "phone": "555-555-5555",
#         "email": "abc123@gmail.com",
#         "specilization": "roofing",
#         "contractor_license_number": "12345",
#         "insurance": "Progressive",
#         "insurance_type": "workers",
#         "coverage": "full",
#         "experience": "10 years",
#         "management_experience": "yes",
#         "employees": "5",
#         "projects": "5",
#         "past_projects": "5 past projects",
#         "job_capacity": "can take on 3 jobs",
#         "recent_jobs": "2 recent jobs",
#         "sow": "N/A",
#         "job_address": "123 four street",
#         "job_bid": "earned",
#         "materials_labor": "123",
#         "warranties": "yes we provide",
#         "warranties_length": "24 months",
#         "sub_contractor": "4",
#         "licensed_insured": "yes",
#         "electrician": "yes",
#         "plumber": "no",
#         "certificates_licenses": "abcd",
#         "bbb_coc": "121",
#         "bankruptcy": "never",
#         "communication": "clear communication",
#         "clean": "yes we clean",
#         "lien_waiver": "yes we sign",
#         "references": "david johnson",
#         "lead_source": "facebook"
#     })

# Investor.create({
#      "first_name": "Joe",
#      "last_name": "Rogan",
#      "street_address": "asdfgh street",
#      "city": "newark",
#      "state": "NJ",
#      "zip": "07111",
#      "phone": "555-555-5555",
#      "email": "abced123@gmail.com",
#      "personal_funds": "$100K",
#      "ira_funds": "$245k",
#      "business_funds": "$600k",
#      "liquid_funds": "$350k",
#      "length_terms": "1 year with monthly payments",
#      "payments": "payments are required after submitting receipts of purchase of materials and labor",
# })

Property.create({
    "first_name": "John",
    "last_name": "Smith",
    "street_address": "123 Madison Ave",
    "city": "Irvington",
    "state": "NJ",
    "zip": "07111",
    "phone": "555-555-5555",
    "email": "abc@gmail.com",
    "asking_price": "100,000",
    "listed": "Not listed with a realtor"
})

    puts "Seeded database"